###

POST http://localhost:8080/sub
Content-Type: text/plain

my value

###

GET http://localhost:8080/sub

###

###

POST http://localhost:8080/composition
Content-Type: text/plain

my value

###

GET http://localhost:8080/composition

###

###

PATCH http://localhost:8080/composition/4f5e669b-fe7d-4543-ae97-2d8b900ad3de
Content-Type: text/plain

my new value

###